config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users

  resources :posts, only: %i(create destroy)
  resource :users, only: %i(show)
  resources :groups do
    resources :posts, only: %i(create destroy)
    resource :comments, only: %i(create)
  end
  resources :comments, only: %i(create edit update destroy)
  resources :user_groups, only: %i(create destroy)
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_tree order: "created_at ASC"

  ATTRIBUTE_PARAMS = %i(user_id post_id parent_id content).freeze

  belongs_to :user
  belongs_to :post

  validates :content, presence: true

  def belong_to? user
    self.user_id == user.id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: %i(edit update destroy)

  def create
    @comment = if params[:comment][:parent_id].to_i > 0
                find_comment_parent
              else
                 Comment.new comment_params
              end

    if comment.save
      @post = comment.post
      respond_to do |format|
        format.html{redirect_to :back}
        format.js
      end
    else
      flash[:danger] = t ".messages.create_failed"
      redirect_to root_url
    end
  end

  def edit; end

  def update
    @comment.update_attributes comment_params
    if comment.save
      respond_to do |format|
        format.html{redirect_to :back}
        format.js
      end
    else
      flash[:danger] = t ".messages.update_failed"
      redirect_to root_url
    end
  end

  def destroy
    if @comment.descendants.any?
      comment.descendants.each do |comment_des|
        comment_des.destroy
      end
    end

    if comment.destroy
      respond_to do |format|
        format.html{redirect_to :back}
        format.js
      end
    else
      flash[:danger] = t ".messages.delete_failed"
      redirect_to root_url
    end
  end

  private

  attr_reader :comment

  def comment_params
    params.require(:comment).permit Comment::ATTRIBUTE_PARAMS
  end

  def find_comment_parent
    parent = Comment.find_by id: (params[:comment].delete :parent_id)
    if parent.present?
      parent.children.build comment_params
    else
      flash[:danger] = t ".messages.not_found"
      redirect_to root_url
    end
  end

  def find_comment
    @comment = Comment.find_by id: params[:id]

    return if comment
    flash[:danger] = t ".messages.not_found"
    redirect_to root_url
  end
end

app/views/comments/_comment.html.erb
<!-- Root Comment-->
<div class="media response-info div-comment-<%= "comment-#{comment.id}" %> ">
  <div class="media-left response-text-left">
    <%= link_to "#" do %>
      <%= gravatar_for comment.user %>
    <% end %>
    <h5><%= comment.user.name %></h5>
  </div>

  <div class="media-body response-text-right">
    <p class="content-<%= "comment-#{comment.id}" %>"><%= comment.content %></p>
    <p>
      <% if signed_in? %>
        <span>
          <%= link_to t(".reply"), "#", class: "comment-form-reply",
            data: {id_cm: comment.id} %>
        </span>|
      <% end %>

      <% if signed_in? && comment.belong_to?(current_user) %>
        <span>
          <%= link_to t(".edit"), edit_comment_path(comment), remote: true,
            class: "comment-form-edit" %>
        </span>|
      <% end %>

      <% if signed_in? && (comment.belong_to?(current_user) || current_user.is_post_owner?(comment))%>
        <span>|
          <%= link_to t(".delete"), comment_path(comment), method: "delete", remote: true,
            class: "comment-form-delete" %>
        </span>|
      <% end %>

      <span><%= time_ago_in_words comment.created_at %></span>
    </p>
  </div>
</div>
<!-- Root Comment-->

<!-- Sub Comment -->
<div class="media response-info">
  <div class="subcomment-<%= "comment-#{comment.id}" %>">
    <% if comment.children.present? %>
      <%= render partial: "comments/subcomment", collection: comment.children %>
    <% end %>
  </div>
</div>
<!-- Sub Comment -->

<!-- form -->
<div class="media response-info">
  <% if signed_in? %>
    <div class="form-initial-load comment-form-<%= "#{comment.id}"%>">
      <div class="media-body response-text-right comment-post">
        <% if comment.root? %>
          <%= render "comments/form", new_comment: comment.children.build,
            parent_id: comment.id, post: comment.post %>
        <% else %>
          <%= render "comments/form", new_comment: comment.root.children.build,
            parent_id: comment.parent_id, post: comment.post %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<!--form  -->

<!-- form -->
<div class="media response-info">
  <% if signed_in? && comment.belong_to?(current_user) %>
    <div class="form-initial-load edit-comment-form-<%= "#{comment.id}"%>">
      <div class="media-body response-text-right comment-post">
        <%= render "comments/form", new_comment: comment, post: comment.post,
          post_id: comment.post.id, parent_id: comment.parent_id %>
      </div>
    </div>
  <% end %>
</div>
<!--form  -->

app/views/comments/_form.html.erb
<% if signed_in? %>
  <%= form_for new_comment, class: "comment-post", remote: true do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.hidden_field :parent_id, value: parent_id %>
    <p>
      <%= f.text_area :content, class: "comment_content", cols: 60, rows: 3, require: "true" %>
    </p>
    <p><%= f.submit t(".comment"), class: "btn btn-primary"%></p>
  <% end %>
<% end %>

app/views/comments/_subcomment.html.erb
<% unless subcomment.new_record? %>
  <div class="row subcomment div-comment-<%= "comment-#{subcomment.id}" %> "">
    <div class="col-md-2">
      <%= gravatar_for subcomment.user %>
    </div>
    <div class="col-md-10">
      <span class="timestamp">
        <%= subcomment.user.name %>
      </span><br/>
      <p class="content-<%= "comment-#{subcomment.id}"%>"><%= subcomment.content %><p>
      <nr>
      <p class="text-right"><%= time_ago_in_words subcomment.created_at %></p>
      <p>
        <% if signed_in? %>
          <span>
            <%= link_to t(".reply"), "#", class: "comment-form-reply",
              data: {id_cm: subcomment.parent_id} %>
          </span>|
        <% end %>

        <% if signed_in? && subcomment.belong_to?(current_user) %>
          <span>
            <%= link_to t(".edit"), edit_comment_path(subcomment),
               remote: true, class: "comment-form-edit" %>
          </span>|
        <% end %>

        <% if signed_in? && (subcomment.belong_to?(current_user) || current_user.is_post_owner?(subcomment))%>
          <span>
            <%= link_to t(".delete"), comment_path(subcomment), method: "delete", remote: true,
              class: "comment-form-delete" %>
          </span>|
        <% end %>
      </p>
    </div>
  </div>
<% end %>

<!-- form -->
<% if signed_in? && subcomment.belong_to?(current_user) %>
  <div class="form-initial-load edit-comment-form-<%= "#{subcomment.id}"%>">
    <div class="media-body response-text-right comment-post">
      <%= render "comments/form", new_comment: subcomment, post: subcomment.post,
        post_id: subcomment.post.id, parent_id: subcomment.parent_id %>
    </div>
  </div>
<% end %>
<!-- form -->

app/views/comments/create.js.erb
var comment_field = '<%= j render @comment, new_comment: @comment.children.build, post: @comment.post %>';
var subcomment_field = '<%= j render(:partial => "comments/subcomment", :locals => {subcomment: @comment, new_comment: @comment.children.build, post: @comment.post}) %>';
<% if @comment.root? %>
  $('.<%= "comment-post-#{@comment.post_id}" %>').prepend(comment_field);
  $('.<%= "post-form-#{@comment.post_id}" %>').toggle();
<% else %>
  $('.<%= "subcomment-comment-#{@comment.parent_id}" %>').append(subcomment_field);
  $('.<%= "comment-form-#{@comment.parent_id}" %>').toggle();
<% end %>
$('.comment_content').val('');
$('.<%= "post-#{@comment.post_id}" %> .count_comment').html("<%= @post.comments.size %>");

app/views/comments/destroy.js.erb
$('.<%= "div-comment-comment-#{@comment.id}" %>').slideUp();
$('.<%= "subcomment-comment-#{@comment.id}" %>').slideUp();

app/views/comments/edit.js.erb
$('.<%= "edit-comment-form-#{@comment.id}" %>').toggle();

app/views/comments/update.js.erb
$('.<%= "content-comment-#{@comment.id}" %>').html("<%= @comment.content %>");
$('.<%= "edit-comment-form-#{@comment.id}" %>').toggle();