config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users

  resources :posts, only: %i(create destroy)
  resource :users, only: %i(show)
  resources :groups do
    resources :posts, only: %i(create destroy)
    resource :comments, only: %i(create)
  end
  resources :comments, only: %i(create edit update destroy)
  resources :user_groups, only: %i(create destroy)
end

app/models/group.rb
class Group < ApplicationRecord
  ATTRIBUTE_PARAMS = %i(name creator_id picture).freeze

  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :posts

  mount_uploader :picture, PictureUploader

  validates :name, presence: true

  scope :order_by_time, -> {order created_at: :desc}

  def order_post_by_time
    posts.order_by_time
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :load_group, only: %i(show destroy edit update)
  before_action :load_view_support, only: %i(show)

  def index
    @groups = Group.includes(:posts, :users).order_by_time.page(params[:page]).
      per Settings.group_per_page
  end

  def new
    @group = Group.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @group = Group.new group_params
    group.users << current_user
    if group.save
      flash[:sucesss] = t "messages.created_group"
    else
      flash[:danger] = t "messages.create_group_fail"
    end
    redirect_to groups_path
  end

  def show
    if signed_in?
      @leave_group = current_user.user_groups.find_by group_id: @group.id
    end
    @posts = @group.order_post_by_time.includes(:user, :comments).
      page(params[:page]).per Settings.post_per_page
  end

  def edit; end

  def update
    if group.update_attributes group_params
      flash[:sucess] = t "messages.update_group"
    else
      flash[:danger] = t "messages.update_group_fail"
    end
    redirect_to groups_path
  end

  def destroy
    if group.destroy
      respond_to do |format|
        format.html {redirect_to groups_path}
        format.js
      end
    end
  end

  private

  attr_reader :group

  def group_params
    params.require(:group).permit Group::ATTRIBUTE_PARAMS
  end

  def load_view_support
    @support = Supports::ViewSupport.new current_user: current_user
  end

  def load_group
    @group = Group.find_by id: params[:id]

    return if group
    flash[:danger] = t "messages.not_found", id: params[:id]
    redirect_to groups_path
  end
end

app/views/groups/_form.html.erb
<div class="modal fade" id="form_modal" role="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for group do |f| %>
      <%= render "shared/error_messages", object: f.object %>
        <div class="modal-header">
          <h4 class="modal-title"><%= t ".new_group" %></h4>
          <h4 class="modal-title text-center"></h4>
        </div>
        <div class="modal-body">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
          <%= f.hidden_field :creator_id, value: current_user.id %>
        </div>
        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">
            <%= t ".close" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_group.html.erb
<div id="<%= "group-#{group.id}" %>">
  <div class="container-fluid">
    <div class="row mm-top">
      <div class="col-sm-4 ">
        <ul class="list-group">
          <li class="list-group-item active">
            <%= link_to group.name, group_path(group) %>
            <div class="pull-right">
              <% if signed_in? && current_user.id == group.creator_id %>
                <%= link_to edit_group_path(group), remote: true do %>
                <span class="glyphicon glyphicon-edit"></span>
                <% end %>
                |
                <%= link_to group_path(group), method: :delete,
                  data: {confirm: t(".sure")}, remote: true do %>
                  <span class="glyphicon glyphicon-remove"></span>
                  <% end %>
              <% end %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/groups/_join_form.html.erb
<% if signed_in? && current_user.is_group_creator?(group) %>
  <div id="join-form">
    <% if signed_in? && current_user.join?(group) %>
      <%= render "leave_group", leave_group: @leave_group %>
    <% else %>
      <%= render "join_group" %>
    <% end %>
  </div>
<% end %>

app/views/groups/_join_group.html.erb
<%= form_for :user_group, url: user_groups_path, remote: true do |f| %>
  <%= f.hidden_field :group_id, value: params[:id] %>
  <%= f.submit t(".join"), class: "btn btn-primary" %>
<% end %>

app/views/groups/_leave_group.html.erb
<%= form_for leave_group, html: {method: :delete}, remote: true do |f| %>
  <%= f.hidden_field :group_id, value: params[:id] %>
  <%= f.submit t(".leave"), class: "btn btn-primary" %>
<% end %>

app/views/groups/_post.html.erb
<% posts.each do |post| %>
  <div id="<%= "post-#{post.id}" %>">
  <div class="well">
    <div class="to-group">
      <%= post.user.name %><i class="glyphicon glyphicon-play"></i>
      <%= link_to group.name, group %>
    </div>
    <div class="media comment-post">
      <div class="media-body">
        <h4 class="media-heading"></h4>
        <p><%= post.content %></p>
        <% if post.picture? %>
          <%= image_tag (post.picture.url), class: "post-image" %>
        <% end %>
        <br>
        <ul class="list-inline list-unstyled">
          <li><span><i class="fa fa-clock-o"></i>
            <%= time_ago_in_words post.created_at %></span>
          </li>
          <li>|</li>
            <span><i class="fa fa-comment"></i>
              <%= t ".comments" %>
              <span class= "count_comment">
                <%= post.comments.size %>
              </span>
            </span>
          <li>|</li>
          <% if signed_in? %>
            <%= link_to "Reply", "#", class: "post-form-reply",
              data: {id_post: post.id} %>

            <% if post.belong_to? current_user %>
              <li>|</li>
                <%= link_to t(".delete"), post, method: :delete,
                  data: {confirm: t(".sure")}, remote: true %>
            <% end %>
          <% end %>
          <p class="text-right"> <%= t ".by" %> <%= post.user.name %></p>
        </ul>
      </div>
    </div>

    <div class="media comment-post">
      <h4 class="comment-post"><%= t ".response" %></h4>
      <div class="comment-<%= "post-#{post.id}" %>-form">
        <% if signed_in? %>
          <div class="media response-info form-initial-load post-form-<%= "#{post.id}" %>">
            <div class="media-left response-text-left">
              <%= link_to "#" do %>
                <%= gravatar_for current_user %>
              <% end %>
              <h5><%= current_user.name %></h5>
            </div>
            <div class="media-body response-text-right">
              <%= render "comments/form", post: post, parent_id: nil, new_comment:
                new_comment %>
            </div>
          </div>
        <% end %>

        <% if post.find_comments_root_post %>
          <%= render partial: "comments/comment", post_id: post.id,
            collection: post.find_comments_root_post %>
        <% end %>
      </div>
      <div class="comment-<%= "post-#{post.id}" %>"></div>
    </div>
  </div>
</div>
<% end %>

app/views/groups/destroy.js.erb
$('#group-<%= "#{@group.id}" %>').slideUp();

app/views/groups/edit.js.erb
$('#myModal').html('<%= j render "form", group: @group %>');
$('#form_modal').modal('show');

app/views/groups/index.html.erb
<h1 class="text-center"><%= t ".all_groups" %> <br></h1>
<% if signed_in? %>
  <%= link_to new_group_path, remote: true, class: "btn btn-primary" do %>
    <span class="glyphicon glyphicon-plus-sign"></span>
    <%= t ".create_group" %>
  <% end %>
<% end %>
<div id="myModal"></div>
<% if @groups.any? %>
  <%= render @groups %>
<% end %>
<br>
<div class="text-center">
  <%= paginate @groups, theme: "twitter-bootstrap-3" %>
</div>

app/views/groups/new.js.erb
$('#myModal').html('<%= j render "form", group: @group %>');
$('#form_modal').modal('show');

app/views/groups/show.html.erb
<h1 class="text-center" > <%= @group.name %> </h1>
<% if @group.picture? %>
  <%= image_tag (@group.picture.url), class: "image" %>
<% end %>
<%= render "join_form", group: @group %>
<div id="post-form">
  <% if signed_in? && current_user.join?(@group) %>
    <%= render "shared/post_form", new_post: @support.current_user_posts_build %>
  <% end %>
</div>
<ol>
  <%= render "post", posts: @posts, group: @group,
    new_comment: @support.init_comment %>
</ol>
<div class="text-center">
  <%= paginate @posts, theme: "twitter-bootstrap-3" %>
</div>