config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users

  resources :posts, only: %i(create destroy)
  resource :users, only: %i(show)
  resources :groups do
    resources :posts, only: %i(create destroy)
    resource :comments, only: %i(create)
  end
  resources :comments, only: %i(create edit update destroy)
  resources :user_groups, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-top">
    <div class="col-md-4 footer-grid">
      <h4><%= t ".mess_us" %></h4>
      <ul class="bottom">
        <li><i class="fa fa-home"></i><%= t ".available_time" %> </li>
        <li><i class="fa fa-envelope"></i><%= t ".email" %></li>
      </ul>
    </div>
    <div class="col-md-4 footer-grid">
      <h4><%= t ".location" %></h4>
      <ul class="bottom">
        <li><i class="fa fa-map-marker"></i><%= t ".address" %></li>
        <li><i class="fa fa-phone"></i><%= t ".phone" %></li>
      </ul>
    </div>
    <div class="clearfix"> </div>
  </div>
</div>

app/views/layouts/_left_menu.html.erb
<div class="col-md-3 top-nav">
  <div class="logo">
    <a href="index.html"><h1><%= t ".blogger" %></h1></a>
  </div>

  <div class="top-menu">
    <span class="menu"> </span>
    <ul class="cl-effect-16">
      <li>
        <%= link_to t(".groups"), groups_path, data:{hover: t(".groups")} %>
      </li>
      <li>
        <%= link_to t(".home"),  edit_user_registration_path, data:{hover: t(".home")} %>
      </li>
      <li>
        <%= link_to t(".home"), "#", data:{hover: t(".home")} %>
      </li>
      <li>
        <%= link_to t(".home"), "#", data:{hover: t(".home")} %>
      </li>
      <li>
        <%= link_to t(".home"), "#", data:{hover: t(".home")} %>
      </li>
      <li>
        <%= link_to t(".home"), "#", data:{hover: t(".home")} %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_top_menu.html.erb
<div class="h-top" id="home">
  <div class="top-header">
    <ul class="cl-effect-16 top-nag">
      <li><%= link_to t(".home"), root_path, data:{hover: t(".home")} %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to t(".log_out"), destroy_user_session_path, method: :delete,
            data:{hover: t(".log_out")} %>
        </li>
        <li>
          <%= link_to t(".my_profile"), users_path(current_user),
            data:{hover: t(".my_profile")} %>
        </li>
      <% else %>
      <li>
        <%= link_to t(".menu.registration"),new_user_registration_path,
          data:{hover: t(".registration")} %>
      </li>
      <li>
        <%= link_to t(".login"), user_session_path,
          data:{hover: t(".login")} %>
      </li>
      <% end %>
    </ul>
    <div class="search-box">
       <div class="b-search">
        <form>
          <input type="text" value="Search">
          <input type="submit" value="">
        </form>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookGroup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/top_menu"%>
    <div class="full">
      <%= render "layouts/left_menu"%>
      <div class="col-md-9 main">
        <%= yield %>
        <div class="clearfix"> </div>
        <%= render "layouts/footer"%>
      </div>
      <div class="clearfix"> </div>
    </div>
  </body>
</html>